### ISSUE TITLE
Typedef extending shows error.

### ISSUE THREAD

**Issue by barisyild** [HaxeFoundation/intellij-haxe#1168]
### Case 1
```haxe
package ;

typedef TypedefInt = {
    var int:Int;
}

typedef TypedefFinal = {
    > TypedefInt;
}

class TestClass {
    public static function init() {
        var typedefFinal:TypedefFinal;
        trace(typedefFinal.int);
    }
}
```
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/25794892/35ab5c78-cb9e-4b1f-ae9f-c710e5ab5c58)

### Case 2
```haxe
package ;

typedef TypedefInt = {
    var int:Int;
}

typedef TypedefFinal = {
    > TypedefInt,
}

class TestClass {
    public static function init() {
        var typedefFinal:TypedefFinal;
        trace(typedefFinal.int);
    }
}
```
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/25794892/e7f43730-af87-4004-afc6-cd14c87b10dc)

**Single typedef extending shows an error, but if you add a variable below it as in the image below, the problem disappears.**

![image](https://github.com/HaxeFoundation/intellij-haxe/assets/25794892/bc1c7e39-db10-48fa-b0db-e08ac251c812)

### Case 3
```haxe
package ;

typedef TypedefInt = {
    var int:Int;
}

typedef TypedefString = {
    var string:String;
}

typedef TypedefFinal = {
    > TypedefInt;
    var a:String;
    > TypedefString;
    var b:String;
}

class TestClass {
    public static function init() {
        var typedefFinal:TypedefFinal;
        trace(typedefFinal);
        trace(typedefFinal);
    }
}
```
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/25794892/1d40e4fc-bd54-4e37-b07d-7c2bd230ff3f)

**However, if you extend more than one typedef as in the image, adding variables does not solve the problem.**

**Comment by m0rkeulv** [comment]
neither Case 1 nor Case 3 seems to be valid Haxe code when trying to compile it with try.haxe.org

Case 1 is incorrect because you should not use `;`  the fact that it removes the error highlighting when ; is added is probably just a bug, it should be `,`
Case 2  while strange code (typdef extending without adding anything) compiles fine  so the parser might need some tweaks.
Case 3 will not work, all extends must be before any new members are added as far as i know.

i would recommend using the Haxe 4 syntax  unless you need to target to target 3.x
https://haxe.org/manual/types-structure-extensions.html
