### ISSUE TITLE
Double-click select word wrong behavior

### ISSUE THREAD

**Issue by fzzr-** [HaxeFoundation/intellij-haxe#212]
Double-click must select **one word** in any expression.
Instead it we have unpredictable behavior:

![dclick mov opt](https://cloud.githubusercontent.com/assets/888526/6996570/8de9557a-db97-11e4-9ba7-dfb9623f4344.gif)
In this demo I use only:
- double-click for demonstration issue;
- single click for deselecting text;

Also: full string (expr) must be selected on triple-click if needed but not on double-click.

TIR: STB-9373

**Comment by fzzr-** [comment]
Works correctly (better) in latest release.

**Comment by sganapavarapu1** [comment]
This works for most cases except for strings - 
still does not allow me to select individual words inside a string literal.

`var foo = "one two three four five";`

if I place cursor on any single-word inside that string and double-click, it will select entire string - needs to be fixed

**Comment by EricBishton** [comment]
Fixes in #644.

**Comment by EricBishton** [comment]
There is still one weird circumstance that occurs, but it's a very limited edge case:  If you double-click on the second asterisk at the beginning of a doc comment, only the text of the comment will be selected.  (In the normal case, when selecting a beginning or end token, the selection will be extended to entire lines if they are multi-line comments.)  This is because the Java comment selectioner (a horrible name) also handles the selection, and IDEA takes the most specific (smallest) one.  We could eliminate that if we changed doc comments to NOT be PsiComments, but that brings with it many other issues.

I'm going to close this.  The functionality will be in the next release.
