### ISSUE TITLE
Support the logic shift assignment operator : >>>=

### ISSUE THREAD

**Issue by soywiz** [HaxeFoundation/intellij-haxe#287]
```
myvariable >>>= 1;
```

This is the same as:

```
myvariable = myvariable >>> 1;
```

And now causes an error: <prefix expression> expected, got '='

TIR: STB-10528

**Comment by as3boyan** [comment]
If I recall correctly then we had same issue before and fixed it, need to check it and add a test case

**Comment by EBatTiVo** [comment]
The old error was #42.  The change implemented was 557bbaa792cea3fa0d1967d7c463abcb401459ae.

**Comment by EBatTiVo** [comment]
I've added a number of test cases for parsing the shift and shift-assign operators.  The right-shift-assign and unsigned-right-shift-assign tests currently fail.  However, once the bug is fixed, the tests will continue to fail until the golden masters are updated.  Look for them on the branch "Fix287ErrorParsingUnsignedRightShiftAssignmentOperator".

I've also taken a look at the old fix, and I'm thinking that we should revert it, add the right-shift-assignment tokens back in and move the operator parsing rules below the genericParam and typeParam rules.  That way the types will have preference and the tokens will be useful again.

I've also noticed that with the current implementation using ('>' '>' '='), we will match "> > =" as a right-shifit operator, whereas the compiler disallows that construct.

@as3boyan I'm going to let you take a look and see if you agree before I go any further down that path.  Feel free to fix it if you so desire.  I'll wait until I hear from you.

**Comment by as3boyan** [comment]
@EBatTiVo Yeah sure

**Comment by as3boyan** [comment]
>I've also noticed that with the current implementation using ('>' '>' '='), we will match "> > =" as a right-shifit operator, whereas the compiler disallows that construct.

Works for me
http://try.haxe.org/#9cDC1

**Comment by EBatTiVo** [comment]
No, it doesn't:  http://try.haxe.org/#C9892
Press "build & run" and you get:
```
Build failure
Test.hx:5: characters 12-13 : Unexpected >
Test.hx:5: characters 12-13 : Unexpected >
```

Yes, the compiler accepts ">>=", but not "> > =" (embedded spaces).

**Comment by as3boyan** [comment]
Ok, I see, we had some issues with spaces

**Comment by EBatTiVo** [comment]
> I've also taken a look at the old fix, and I'm thinking that we should revert it, add the right-shift-assignment tokens back in and move the operator parsing rules below the genericParam and typeParam rules in the BNF. That way the types will have preference and the tokens will be useful again.

@as3boyan Do you have another plan in mind than this?

**Comment by as3boyan** [comment]
We had some issue with "=" but I don't remember if it is related to this issue.

**Comment by EBatTiVo** [comment]
Here is another solution that showed some promise:  Treating '<' and '>' as if they were string delimiters.


[Fix287ByAddingLexerState.zip](https://github.com/TiVo/intellij-haxe/files/673669/Fix287ByAddingLexerState.zip)
