### ISSUE TITLE
Cannot resolve enum parameter symbols at case statement

### ISSUE THREAD

**Issue by keroxp** [HaxeFoundation/intellij-haxe#351]
when enum as follows is defined, 
<img width="374" alt="2015-09-16 20 50 45" src="https://cloud.githubusercontent.com/assets/927286/9903934/f4f2b0c4-5cb4-11e5-826c-24d1088367a7.png">
IntelliJ IDEA cannot resolve enum parameter at case statement.
<img width="601" alt="2015-09-16 20 51 15" src="https://cloud.githubusercontent.com/assets/927286/9903935/f4fcbeac-5cb4-11e5-8275-305f8f11136b.png">

thanks :)

**Comment by nadako** [comment]
Not only in cases, but any unqualified name is not supported:

![](https://i.imgur.com/GLoYX7q.png)

Very annoying :(

Rules that the compiler uses are something like that:
 - if the expected type is known and is an enum - try resolving identifier against that enum (so you don't even need to import it)
 - if an enum is imported into the module, its constructors are also available in that module's namespace (so if you have a module `M.hx` with `enum E { A; B; }`, when you do `import M.E;` you have `A` and `B` available, and it's the same if you import the whole module with `import M;`, because then all module types are imported and the enum rule applies).

**Comment by nadako** [comment]
pretty please? :)

**Comment by mayakwd** [comment]
Almost done

**Comment by nadako** [comment]
Thanks!
