### ISSUE TITLE
Status of compiler-based completion

### ISSUE THREAD

**Issue by elsassph** [HaxeFoundation/intellij-haxe#367]
A "quick win" to overcome some of IntelliJ's built-in completion limitations is to add compiler-based completion in parallel to the built-in one.

I've heard that some things are in fact implemented, however the limitations and required project configuration are rather mysterious.

 Could you:
- provide some feedback / a test project so people can try using it,
- recommend where to look in the plugin source code to contribute.

**Comment by EBatTiVo** [comment]
The way IDEA is implemented, it runs a loop across all registered completion engines.  So, both the compiler engine and the word-based one are in play at all times; in parallel as you say.  It's also the case that every other installed completion engine (for every plugin) is called (and that's why too many plugins slows down your whole IDEA experience).  It's up to the completion engine to decide whether it's appropriate to try and match the input to come up with results.  That usually happens by the engine checking the type of file, or -- for advanced plugins -- to decide if the request was in an embedded language (e.g. Javascript inside HTML, assembly inside of C, etc.).  If I remember correctly, the loop does not terminate at the result of one of registered handlers, but always visits all of them, building up an array.

In the case of Haxe, the compiler completion doesn't get many results because (at least with the 3.1 compiler) it requires that the completion point be in a "syntactically invalid" position -- of which there are only a few recognized.  One of them is immediately after a dot, but it will not work if a partial identifier is formed (meaning it won't work if you type the first two letters of an identifier and then request completion).  The solution is fairly simple, look for the previous position that is valid for the compiler to check, and then filter the list after the results have come back.

In order to find the completion position, we don't have to re-parse the text to the left of our current editing position.  We only have to check if our current editor token is a HAXE_TOKEN (PsiHaxeToken) containing the text '.', and calculate the position immediately to the right of it as the completion point, or follow the tree up to the point where the dot appears as the left sibling if the current token is a PSI_IDENTIFIER.  After that, it may be necessary to add a dummy identifier (containing space as the text) into the PSI tree while we make the completion request, and remove it afterward.  Finally, we filter the results by the text of the current identifier, if any, to limit the display to those tokens matching the user's partial input.  Beware that IDEA normally uses a regular expression match (for camel case searches, etc.) and we have to duplicate the functionality or users will complain.

The file that implements compiler-based completion is called, fittingly enough, HaxeCompilerContributor.java.

**Comment by elsassph** [comment]
Ok I think I figured how to trigger the haxe compiler completion - at least using direct configuration (`Compile with [X] Haxe Compiler`) and external (`Compile with [X] HXML`). Not sure if it would work with an external toolchain like OpenFL as well.

It is indeed very difficult to use because it not only is limited to when you type a dot, but you apparently must generally save the file (with the dot) before deleting/re-typing the dot and then you get completion.

**Comment by EricBishton** [comment]
Compiler completions were implemented with the 0.11.0.
