### ISSUE TITLE
Feature request: Find references on class constructor

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/intellij-haxe#530]
The request is to support looking up references, based on a class constructor:

```haxe
                 Search for usages
                 ^
public function new () {


}
```

---

Flowplay is interested in paying to support the development of this and other issues:

https://github.com/TiVo/intellij-haxe/issues/528
https://github.com/TiVo/intellij-haxe/issues/529
https://github.com/TiVo/intellij-haxe/issues/531

Thanks everyone :smile:

**Comment by mayakwd** [comment]
It's not too easy to achieve that. Grammar of haxe parser based on wrappers and have a lot of overhead above existing psi-types. HaxeNewExpression should extend PsiNewExpression to participate in usage process, but it can't, because of HaxeType not extending PsiType (HaxeType is PsiElement, but PsiType is not PsiElement).

**Comment by EricBishton** [comment]
I've got an idea how to do it, and I'll be working on this soon.

**Comment by mayakwd** [comment]
I guess it could be closed
