### ISSUE TITLE
Completion is REALLY SLOW

### ISSUE THREAD

**Issue by bruno-ortiz** [HaxeFoundation/intellij-haxe#559]
I'm trying to use this plugin but the auto completion is really slow, and makes typing a pain. Whenever i'm typing, the IDE takes several milliseconds to draw my input.

Someone have any advices on how to improve that? Or is this a bug?

I'm using:
IDEA 2016.3.4
Windows 10 64 bits
Haxe 3.4.0

Thx!

**Comment by EricBishton** [comment]
Yes, this is a problem with the pre-built test.  Completion works, but the thread running it isn't canceling properly when the user starts typing.  I've fixed this in the latest sources, and I'll make a new test build soon.

**Comment by bruno-ortiz** [comment]
Sorry, i forgot to mention, the version im using is  0.10.1.1, installed from the IDE repositories.

**Comment by b005t3r** [comment]
I do have the same problem with auto-completion. It's not that awful, but it's also not as convenient as with Java/Flash.

**Comment by EricBishton** [comment]
Would you guys be willing to test a build from a feature branch?

https://github.com/HaxeFoundation/intellij-haxe/releases/tag/10.1.Test.CompilerCompletion

This does have compiler completion included, but it also has better canceling code, so it doesn't get in the way of your typing.  You should try it with compiler completion turned both on and off and let me know if either way still gives you the typing issue.  (BTW, CC isn't quite done yet, and when doing completion, the compiler sometimes complains about spurious errors that don't occur during a regular compile.)

**Comment by b005t3r** [comment]
I tried it, it's much better, no difference from Java or Flash projects. I'm not sure how to turn off the completion.

And one more thing about the new plugin, please change this flashy Haxe icon - make it smaller at least with transparent bg :)

![image](https://cloud.githubusercontent.com/assets/757150/23209567/04161ae0-f8fa-11e6-821b-e720d69156a2.png)

**Comment by b005t3r** [comment]
Ah, sorry, I am an idiot. What I wrote before was with compiler completion OFF.

Now I turned it ON and maybe, but really maybe I need to wait a bit longer for it to give me symbols list. It has some bugs however:

* symbols shown twice:
![image](https://cloud.githubusercontent.com/assets/757150/23209749/cb6cc0f8-f8fa-11e6-8b47-1166a90fce12.png)

* symbols not properly formatted (part of the declaration and comment visible):
![image](https://cloud.githubusercontent.com/assets/757150/23209773/ec895ef4-f8fa-11e6-921c-d85bf14f496a.png)

Other than that it looks like it works :) I'll leave it on and let you know if I find something else.

**Comment by EricBishton** [comment]
So, the duplicated entries are because the ones with the Haxe logo are provided by the compiler, and the others are provided by the plugin.  Dropping the duplicates is interesting because most of the time (at least using type parameters) they are not the same.  The compiler replaces the type parameter with the actual type being used, rather than the parameter name like the plugin does.  In order to fully remove duplicates, we would have to know the type that the parameter turns into (and we need the compiler for that).  So, totally removing duplicates may be harder than one would think.  That said, we can at least try, but that requires that the plugin take control of the completion process away from IDEA and manage all of the contributors itself -- not impossible, just different and possibly error prone (and not recommended by JetBrains).

Note the bottom line of the dropdown.  It's telling you that the compiler hit an error that prevented it from giving completion results.

**Comment by b005t3r** [comment]
Also I noticed that results from compiler ofter have the type set to Unknown where type inference is used - it's a bit strange that the compiler can't figure out the type, which it can do while building the project.

**Comment by bruno-ortizgb** [comment]
Wow, its really better now! 

I didn't have the problems with the symbols showing twice. Maybe i did something wrong?

**Comment by arthurferrai** [comment]
I tried test version right now and completion performance improved a lot (compared to official plugin). Over here, no duplicated symbols for now.

**Comment by EricBishton** [comment]
Since this has been reported to be faster, and it's in the 0.11.0-RC3 candidate, I'm going to close this.  
Fixed in 8d5db397ce9e90617c25ed53a5ab4a32b9f0fb3f
