### ISSUE TITLE
Minor releases

### ISSUE THREAD

**Issue by mayakwd** [HaxeFoundation/intellij-haxe#613]
Hello. 
I suggest we should introduce new method of releasing plugin updates. 

That would be very comfortable to let community test new features and give us feedback. At this moment we are not getting any tests and feedbacks from side of users, till critical mass of improvements is released. It's vital for rapid development and improvement of plugin.

**Comment by EricBishton** [comment]
Well, we *do* have a few users who try it out from the builds that I publish on github.  I personally like to try and release every six weeks.  The latest changes that I've been working on, though, are all trying to fix a larger issue that we've had for a few years now.  That's why I'm making all of the RC builds. Well, ...  that, and the folks who usually do code reviews for me haven't had the time, recently.

At any rate, what changes would you suggest?

**Comment by mayakwd** [comment]
I thought of release per week, and plugin is really needs roadmap, it's hard to understand right now - who is working on what. 

Also I have a great passion to improve a lot of things, but merging/declining of pull requests taking too much time, could you suggest something on that point?

**Comment by EricBishton** [comment]
The roadmap is in my head.  :-)  I can try to spend some time writing it down.  At any rate, there isn't much activity beyond myself (and what you've started) at the moment.  Other relatively regular contributors are off doing other things, so it's even hard to get code reviews.  I'll usually put things out there for review and wait two days before making a decision to just pull them anyway.  You are welcome to review my code, too.

I try to review your changes in the mornings and pull them as soon as I approve them.  Sundays are days that I frequently don't get on the computer, so if your main work is on the weekend, then you'll have to wait until Monday.  Since I am in California, that means that you can usually expect me to respond at around 10:00 AM PST, (in other words 6:00 PM UCT)  and I'm usually at my computer all day.  If you want to talk to me at a quicker cycle, we can do email or slack.

**Comment by EricBishton** [comment]
The biggest problem with doing quicker releases is this:  It takes four hours to prep the build (review changes for documentation, update change notes, contributors, docs, etc.)  It takes about a day to smoke test all five of the supported builds (there is a smoke test script in the CONTRIBUTORS.md file) and AFAIK aren't easily automated.  (I'm sure there's software to check dialogs visually, etc., but I haven't researched it and don't have anything set up.)  There is no QE team, so that means me doing the smoke tests by hand.  Thus, it's a day of work to do a release, and I'm not keen on doing that weekly.
