### ISSUE TITLE
Java 8 features

### ISSUE THREAD

**Issue by mayakwd** [HaxeFoundation/intellij-haxe#614]
I really like to use great features of Java 8, e.g. Lambdas, Stream API and so on. It gives less code and more readability. 
What do you think about move from Java 6, to Java 8?

**Comment by EricBishton** [comment]
We still have a contingent of users on older builds.  We have announced that we will be dropping support for 2014 builds toward the end of this year.  But that still leaves us with a year to go until we drop 2015.  Until we decide to abandon the 2015 users, we can't move to Java 8.

**Comment by mayakwd** [comment]
Well, version 2017 released already, and that's a bit odd to sit on the old builds. I guess it's because of moving of Jetbrains to subscription plan.

**Comment by EricBishton** [comment]
Truth to tell, that is a consideration, but a small one, because most folks that don't want to pay for the subscription licensing model are small developers.  The larger population that doesn't move forward very often is the corporate clients.  They want *stable* dev environments because updating their developers work flow is expensive in terms of lost time and opportunity cost.  Basically, the ROI has to be large enough to take the pain of updating, and that means there must be significant new functionality.  Updating a plugin is a much smaller pain point than updating the whole environment.
