### ISSUE TITLE
0.11.0.RC-3 Incorrectly colored text inside a conditional compilation

### ISSUE THREAD

**Issue by SlavaRa** [HaxeFoundation/intellij-haxe#621]
![](http://image.prntscr.com/image/10e599a0c5ce43d3afee56f38f565711.png)

**Comment by EricBishton** [comment]
Working as designed.  When the #if evaluates to false, the code is colored as a comment to show that it's not in use.  You need to update the defined macros in the Project Settings->Modules->Project Macros field.

I've been thinking about better colorization techniques, but they are going to be expensive to run and complex to implement given that they have to re-traverse the file in order to colorize alternate (unused) code.

**Comment by SlavaRa** [comment]
"You need to update the defined macros in the Project Settings->Modules->Project Macros field."
We have more than 40 such flags that are in a separate hxml file. It's not very convenient and it's not obvious to add them somewhere else in the UI of editor.

But ok, Thanks for the answer

**Comment by mayakwd** [comment]
I think we should have another issue - make this feature more obvious and add some intentions to switch quickly between defines.

**Comment by EricBishton** [comment]
A new issue #622 has been filed to start discussion on an enhanced design.

**Comment by RealyUniqueName** [comment]
I don't see how such coloring could help developers. 
It's almost impossible to maintain a list of conditionals in a big project.
What if i build for multiple platforms on every compilation?
What if conditionals are being set dinamically by macros depending on some third-party circumstances?
And it's a common case for me to edit even those parts of code which are not included in a current compilation setup.
I'd like this feature to be disabled by default.

**Comment by cmandlbaur** [comment]
Maybe a blacklist would be preferable to a whitelist?

**Comment by EricBishton** [comment]
So, the trouble is this:  We have a lot of bugs and apparent errors when the parser does not interpret conditionals.  (In fact, the compiler can't compile the code when conditionals are not set properly, so why should we think that the IDE can?)  All of those "unresolved symbols" that everybody complains about are related specifically to not being able to understand conditionals.  The inability to parse and use StringTools is caused by the same issue.  The plugin cannot effectively parse the code through multiple branches and be able to understand them all simultaneously (at least not in a timely fashion).  It cannot effectively run semantic annotation when compiler conditionals are not set.  Find usages, goto definition, etc. cannot find the correct place of definition without knowing _which_ place of definition is the correct one.  Thus, to fix the bugs that we have and to extend the functionality, we need to correctly understand the code.  The highlighting as a comment is a way to show the developer that the plugin isn't working with that block of code when it does the things the user is asking it to do.

Now, as to solutions, I'm very open to suggestions.  I've got some ideas in issue #622 that should make the maintenance burden less and that I would like to pursue.  If you have a proposal, feel free to start a new issue and document your designs in enough detail that I (or another developer) can implement them.  I won't shoot them down just because they aren't mine; I will point out flaws so that we can work toward a workable system.

**Comment by EricBishton** [comment]
@cmandlbaur  I'm not clear on how a black list would solve the problem.  It seems the same one to me: some code has to be ignored, and how do we denote that?

**Comment by cmandlbaur** [comment]
Currently you opt in to flags. It seems like most people who you prefer to opt out of certain flags.

**Comment by EricBishton** [comment]
OK, I can see that I can set the default value of a flag to "true" instead of "false" if it's undefined.  I don't think that falls under the principle of least surprise, but it's worth thinking about.  

How does that help the management of flags?  
Do you presume that there are fewer flags you don't want set, rather than those you do?
How does that help with the colorizing (or non-colorizing as the case may be) of a protected section of code when the user wants to edit within it and it is not in use?
