### ISSUE TITLE
Conditionals body are parsed as comment

### ISSUE THREAD

**Issue by jedcua** [HaxeFoundation/intellij-haxe#646]
This occurs when on version `0.11.0`, using Intellij version `2016.2.5`

Any code between `#if` and `#end` is treated as a comment/conditional. 
Hence, Intellij complains when I try to reference any variable/method declared within that conditional.

Example:

![screenshot from 2017-06-12 13-56-01](https://user-images.githubusercontent.com/11945463/27020860-f63387ea-4f76-11e7-962c-db0216929b37.png)

**Comment by EricBishton** [comment]
That sounds like correct behavior.  If the variable is only created within your "#if mobile" block, then it's only available to reference in places/blocks where "#if mobile" is defined.  (Actually, the plugin is parsing the conditionals to determine which blocks contain valid code, just like the compiler would.)

```haxe
class foo {
  function doSomething() {

    #if (false)
    var myVar = "something.";
    #end

    if (myVar == "else") {    // <---  Error here: myVar is not defined.
      ...
    }
  }
}
```
Obviously, the variable won't be available because of the 'false' case.  In your case, if 'mobile' is not defined, then you are creating the same situation.

If the issue is that _none_ of the blocks that occur inside of 'mobile' guards are available, then you need to set an appropriate value for it (or simply define it) in the "File->Project Structure->Modules->Haxe tab->Project Macros" sub-dialog.

Did I misunderstand the issue you are presenting?

**Comment by jedcua** [comment]
@EricBishton I tried adding the said conditional, and it was now able to display the code body properly.

![screenshot from 2017-06-12 15-50-52](https://user-images.githubusercontent.com/11945463/27023880-00b653b8-4f87-11e7-9fa7-7b40c2ba34f4.png)

I raised this issue because this didn't happened before, only when I updated to version `0.11.0`.

Thank you for responding!

**Comment by EricBishton** [comment]
It's a new feature with 0.11.0.  (Well, to be fair, it's an old feature that was disabled several years ago and re-implemented with this version.)
