### ISSUE TITLE
Flash debugging not working in 0.11.2

### ISSUE THREAD

**Issue by guruas3** [HaxeFoundation/intellij-haxe#712]
After updating to the latest version of the plugin from 0.11.1 to 0.11.2 i have problem with debugging Flash target with OpenFL. The compilation succeeds but then nothing happens and after the first try of debugging flash i can't try again and i need to restart Intellij(then i have same issue). When i uninstalled 0.11.2 and manually installed previous 0.11.1 it started working as it should.

Plugin version 0.11.2
IDEA version 2017.1.3
OS Windows 7

**Comment by EricBishton** [comment]
I have been experimenting with flash debugging and I probably broke something for you.  It doesn't work reliably for many folks.  I am working on things right now.

@guruas3 If you can be more specific as to what happens when you "can't try again" it would be very helpful.  I haven't seen that issue at all.  (Most folks time out trying to start their app after the AIR debugger starts.)

**Comment by guruas3** [comment]
Let me explain that better.
When i do Run->Debug 'myproject' it starts compiling it then it outputs in the console the following message: "Compilation completed successfully in 7s 374ms". Then the flash debugger doesn't open and nothing happens after that.
Then i can't even re-run Run->Debug 'myproject' because the button is disabled
If i go to Run->Debug...(opens pop up to select the project) -> Select 'myproject' -> Debug nothing happens.
To be able to run Debug again i need to restart Intellij. But then again after the first compilation debug is disabled.
I hope i was clear enough.
Thank you for looking into it.

**Comment by pecheny** [comment]
Hi. As for last release seems the debugger can't start because of couple of nullrefs i had fixed last week.
There is a simple way to determine the reason, take a look at the end of Idea's log just after last failed debugger run. (Menu help -> Show Log in Explorer).
However even if debugger runs now there is other issue. Earlier versions of plugin was able to capture compiler output, determine if compilation fails and forward errors to the message window as separate records where double click on each one would open line with error in the editor.
Now all compiler output shown as raw console text and idea launches debugger even if compilation was failed.

**Comment by EricBishton** [comment]
@pecheny - I can't reproduce either the main complaint (which I believe you fixed) or your secondary one using the current sources in master (using IDEA 2017.2 or 2017.3).  Can you please provide the IDEA release/version details, your (IDEA) module configuration settings, and your flash/air/flex SDK details?  Thanks.

**Comment by EricBishton** [comment]
I believe that this was fixed with #750.
@pcheny If you have time to verify, that would be great.

**Comment by guruas3** [comment]
I will be able to test if the problem is gone if you could provide the latest version of the plugin compiled for 2017 version.

**Comment by guruas3** [comment]
@EricBishton yeah sorry i haven't written the feedback after the release. The fixes work great the debugger is working well again. The only problem now is the color highlighting. So i had to go back to 0.11.1 version.

The highlighting problem is about the color of variable names, variable types, class names, function names, imports. All these by default when opening Intellij are white and not colored. when i perform some action like compile project or open file folder it sets the color only to the first top displayed line.
So at the end i got something like this: 
![2018-04-08_1055](https://user-images.githubusercontent.com/981231/38465422-ba9c5630-3b1b-11e8-919d-1920c1016c6c.png)
Because of this i really can't use the latest version. Not sure why do i get this as nobody has mentioned it. I'm using material theme.

P.S. This is another issue with the highlighting so i'm closing this issue. Thanks for your work.
