### ISSUE TITLE
IntelliJ Ultimate Or IntelliJ Community?

### ISSUE THREAD

**Issue by hopewise** [HaxeFoundation/intellij-haxe#717]
I am targeting html5 with openFL, is there any recommendation on using IntelliJ Ultimate or IntelliJ Community version?

**Comment by rickthepick** [comment]
I don't know, but the readme includes the following text:

Use the hxcpp debugger

NOTE: IDEA Community Edition currently will not start an IDE-based debugging session. For that, IDEA Ultimate is required. Command-line debugging is available because that is a feature of the Haxe language itself. See the hxcpp-debugger project for more information."

**Comment by EricBishton** [comment]
I don't have a personal recommendation on that.  I use IntelliJ IDEA Ultimate for creating the plugin and debugging it.  I use the Community Edition sources as debugging sources (because they are a subset and are usually enough to get the job done).  I don't build or use Community Edition myself.

I know that some (large, commercial) projects targeting html5 and OpenFL use Ultimate Edition successfully to build a flash version and use the Flash debugging facility within IDEA.

If you are planning on using source maps and debugging within a browser, then either Edition will work for editing -- neither will open your app in the browser, though.

Finally, the things that I think are missing from CE are being able to start a debug session, class diagrams, class hierarchy (panel) browsing, and source control integration (only git in CE).  There is probably more, but I'm not sure what missing functionality applies to Haxe vs. other languages.
