### ISSUE TITLE
the string "${" breaks parsing

### ISSUE THREAD

**Issue by rickthepick** [HaxeFoundation/intellij-haxe#718]
from haxe manual "Special identifiers, denoted by the dollar sign $ within a String enclosed by single-quote ' characters, are evaluated as if they were concatenated identifiers" (https://haxe.org/manual/lf-string-interpolation.html)

but this is a double quote:

![screen shot 2017-12-21 at 4 23 33 pm](https://user-images.githubusercontent.com/328585/34275460-6d34069a-e66b-11e7-953a-692502cce429.png)

**Comment by EricBishton** [comment]
Yeah, I've seen this code and just haven't gotten around to fixing it.  (It's in the lexer.)  Nobody has complained up to this point.  :smile:

**Comment by rickthepick** [comment]
Yeah it's a pain though cause the rest of the file isn't parsed properly and other files that reference the methods that aren't parsed show "unresolved symbol" errors.

**Comment by EricBishton** [comment]
Actually, I take that back.  @mayakwd and I were having a conversation about this a few weeks ago and I was arguing that we should continue to parse ${} inside of double-quotes so that we could highlight to the user that they were probably using the wrong quote type.  Even if we do, though, it shouldn't break parsing.  :wink:

**Comment by rickthepick** [comment]
Just for fun this is the offending source: https://github.com/haxeui/haxeui-core/blob/master/haxe/ui/core/Component.hx

The code that triggers the issue is parsing - looking for ${ - heh :-D

**Comment by EricBishton** [comment]
Fixed in PR #1055.  Will be released with plugin version 1.4.
