### ISSUE TITLE
Incorrect handling of private methods for "super" visibility.

### ISSUE THREAD

**Issue by soywiz** [HaxeFoundation/intellij-haxe#87]
``` haxe
class Demo {
    private function method1() {
    }
    private function method2() {
    }
    public function method3() {
    }
}

class Demo2 extends Demo {
    override private function method2() {
        super. // <--- HERE you can see just method3, and you should see method1 and method2
    }
}
```

TIR: STB-7311

**Comment by EBatTiVo** [comment]
I see /nothing/ in the suggestions list for the above example.  And I see ```method2()``` and ```method3()``` for the below example.  The issue appears to be that we're using the traditional OO sense of /private/ (hidden from descendants) for detecting whether a method can be called, rather than Haxe's, which is really the traditional /protected/ behavior.

```haxe
// Issue #87
class DemoIssue87 {
    private function method1() {
    }
    function method2() {
    }
    function method3() {
    }
}

class Demo2Issue87 extends DemoIssue87 {
    override private function method2() {
        super. // Here, you can only see non-private parent methods.
    }
}
```

**Comment by as3boyan** [comment]
If I got it right, then look at PR https://github.com/TiVo/intellij-haxe/pull/451

**Comment by as3boyan** [comment]
http://try.haxe.org/#02d98 compiles fine

**Comment by mayakwd** [comment]
It's not reproduceable, guess it's fixed with pr?

**Comment by EricBishton** [comment]
Yep.  Closing.
