### ISSUE TITLE
Can't navigate to implementation

### ISSUE THREAD

**Issue by chrisvelevitch** [HaxeFoundation/intellij-haxe#905]
When I mouse over a method reference (like `super.render`) I can normally `cmd-click` to go to its implementation. However, if the current `class` `extends` a `class` that is defined in a file containing multiple `class` definitions, it doesn't work.

---
IntelliJ 2018.3, Mac OS X 10.13.6 (High Sierra)

**Comment by EricBishton** [comment]
Works for me, using Mac OS X 10.14.2 (Mojave), IDEA 2018.1.5, and the plugin version 1.0.2.  Also, using Win10, IDEA 2018.1.3, and plugin version 1.1 (+, develop branch).

File: TestIssue905_NavigationBrokenWithMultipleClassesInOneSource.hx
```Haxe
package ;

import haxe.ds.BalancedTree;

class TestIssue905_NavigationBrokenWithMultipleClassesInOneSource extends TreeNode<String, String> {
    public function new() {
        super("M", "m");
        trace(super.get_height());
    }
}
```
Can you please test the above code and/or produce a reproducible example?

**Comment by chrisvelevitch** [comment]
I've attached my exported to zip `IntelliJ` test project. You should be able to see that my `Main` class extends `SuperMain` and `SuperMain` is defined in the file `MainExtended.hx`. In `Main` I can't navigate to `SuperMain` nor can I navigate to the function `super` as `cmd-mouseover` doesn't highlight the class name or the function name.

[testcase1.zip](https://github.com/HaxeFoundation/intellij-haxe/files/2776414/testcase1.zip)

**Comment by EricBishton** [comment]
For me, this works properly if the package statements are set correctly for the package directories.  So, it works with `package;` if Main.hx and MainExtended.hx are in a source root, and also if the package is named correctly and the files are in a source tree beyond src.  And the test case is working as well.

It is quite possible that this was fixed at some other point, because there are several classes in std that have the same issue (e.g. Contraints).
