### ISSUE TITLE
CLion

### ISSUE THREAD

**Issue by WolfieWerewolf** [HaxeFoundation/intellij-haxe#935]
Hi Eric,

I was wondering if you could please tell me what I'm doing wrong.  I'm attempting to use the plugin (both the one from the JetBrains plugin repository in CLion and the one I compiled from the development branch from source) with CLion but it's failing.  I get a fairly meaningless stacktrace and the project tree doesn't finish loading.  Is there something specific I need to do?  It would be handy to be able to work on C/C++ and Haxe in the same IDE.  Thanks man.

**Comment by EricBishton** [comment]
Hi Geoffrey,

I haven't actually tried running it in CLion.  I suspect the reason is because the plugin relies on Java support classes that are missing in that product.  There is a similar discussion in issues #378, and #934.  

I can't take a look right at the moment because I'm in the middle of fixing the issues with generics that you reported.  😉  

Can you paste the top 20 lines or so of the stack trace here?

**Comment by WolfieWerewolf** [comment]
(blush) I suspect the other tickets answer it completely.  I'm not really a slave driver I just play one on television ;-).  Thanks Eric.
